#!/usr/bin/env python3
"""Audit one stop-to-stop route candidate with a map-aware built-in vision model.

The model may only approve/reject an existing candidate geometry. It cannot create
new coordinates. Official ETA minutes remain a hard constraint in the prompt and
in the post-response validator.
"""
from __future__ import annotations
import argparse, base64, json, math, os, sys, urllib.parse, urllib.request
from io import BytesIO
from pathlib import Path
from PIL import Image, ImageDraw
from openai import OpenAI

TILE = 256

def get_json(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": "BusPulse-HK-route-audit/1.0"})
    with urllib.request.urlopen(req, timeout=25) as r:
        return json.load(r)

def web_bytes(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "BusPulse-HK-route-audit/1.0"})
    with urllib.request.urlopen(req, timeout=25) as r:
        return r.read()

def xy(lat, lon, zoom):
    n = 2 ** zoom
    x = (lon + 180) / 360 * n
    y = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n
    return x, y

def make_map(a, b, line, zoom=17):
    points = [(a["lat"], a["lng"]), (b["lat"], b["lng"])] + [(p[1], p[0]) for p in line]
    xs, ys = zip(*(xy(lat, lon, zoom) for lat, lon in points))
    minx, maxx = min(xs) - 1.2, max(xs) + 1.2
    miny, maxy = min(ys) - 1.2, max(ys) + 1.2
    left, top = math.floor(minx), math.floor(miny)
    right, bottom = math.floor(maxx), math.floor(maxy)
    img = Image.new("RGB", ((right-left+1)*TILE, (bottom-top+1)*TILE), "white")
    for tx in range(left, right+1):
        for ty in range(top, bottom+1):
            try:
                tile = Image.open(BytesIO(web_bytes(f"https://tile.openstreetmap.org/{zoom}/{tx}/{ty}.png"))).convert("RGB")
                img.paste(tile, ((tx-left)*TILE, (ty-top)*TILE))
            except Exception:
                pass
    draw = ImageDraw.Draw(img)
    def px(lat, lon):
        x, y = xy(lat, lon, zoom)
        return ((x-left)*TILE, (y-top)*TILE)
    route_px = [px(p[1], p[0]) for p in line]
    if len(route_px) > 1:
        draw.line(route_px, fill=(220, 25, 45), width=7, joint="curve")
        draw.line(route_px, fill=(255, 230, 30), width=3, joint="curve")
    for point, color, label in [((a["lat"],a["lng"]),(30,170,80),"A"), ((b["lat"],b["lng"]),(180,20,30),"B")]:
        x,y=px(*point); draw.ellipse((x-9,y-9,x+9,y+9), fill=color, outline="white", width=3); draw.text((x+11,y-12),label,fill="black",stroke_width=2,stroke_fill="white")
    return img

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--from-name", required=True); ap.add_argument("--to-name", required=True)
    ap.add_argument("--from-lat", type=float, required=True); ap.add_argument("--from-lng", type=float, required=True)
    ap.add_argument("--to-lat", type=float, required=True); ap.add_argument("--to-lng", type=float, required=True)
    ap.add_argument("--official-minutes", type=float, required=True)
    ap.add_argument("--out", default="ai-route-audit.json")
    args=ap.parse_args()
    a={"name":args.from_name,"lat":args.from_lat,"lng":args.from_lng}; b={"name":args.to_name,"lat":args.to_lat,"lng":args.to_lng}
    url=("https://router.project-osrm.org/route/v1/driving/" f"{a['lng']},{a['lat']};{b['lng']},{b['lat']}?overview=full&geometries=geojson&steps=false")
    q=get_json(url); route=(q.get("routes") or [None])[0]
    if not route: raise RuntimeError("OSRM returned no candidate")
    line=route["geometry"]["coordinates"]
    img=make_map(a,b,line); buf=BytesIO(); img.save(buf,format="PNG")
    data=base64.b64encode(buf.getvalue()).decode()
    prompt=f"""You are auditing ONE existing bus route candidate between two official stops in Hong Kong.
The red/yellow line is the candidate generated by a road router. Do not invent coordinates or propose a new route.
Official bus-company stop-to-stop ETA is {args.official_minutes:.1f} minutes and is authoritative.
Judge only whether the displayed candidate is physically plausible for a bus: it must follow a motor-vehicle road, not a footway, pedestrian path, building, park, staircase, or open ground. Also reject it if its visible detour is inconsistent with the official ETA. Return JSON only with pass, road_class, time_consistent, confidence, reason.
Stops: {args.from_name} -> {args.to_name}."""
    client=OpenAI(); resp=client.chat.completions.create(model="gemini-3-flash-preview", max_tokens=1000, messages=[{"role":"system","content":"Return JSON only."},{"role":"user","content":[{"type":"text","text":prompt},{"type":"image_url","image_url":{"url":"data:image/png;base64,"+data,"detail":"high"}}]}], response_format={"type":"json_schema","json_schema":{"name":"route_audit","strict":True,"schema":{"type":"object","properties":{"pass":{"type":"boolean"},"road_class":{"type":"string","enum":["vehicle-road","footway","building","mixed","unknown"]},"time_consistent":{"type":"boolean"},"confidence":{"type":"number","minimum":0,"maximum":1},"reason":{"type":"string"}},"required":["pass","road_class","time_consistent","confidence","reason"],"additionalProperties":False}}})
    raw = resp.choices[0].message.content or ""
    try:
        verdict = json.loads(raw)
    except json.JSONDecodeError:
        start, end = raw.find("{"), raw.rfind("}")
        if start < 0 or end <= start: raise
        verdict = json.loads(raw[start:end + 1])
    # Official time is a hard gate even if the model is over-optimistic.
    verdict["pass"] = bool(verdict["pass"] and verdict["time_consistent"] and verdict["road_class"] == "vehicle-road")
    result={"from":a,"to":b,"officialMinutes":args.official_minutes,"osrmDistanceMeters":route.get("distance"),"osrmDurationSeconds":route.get("duration"),"candidate":line,"ai":verdict}
    Path(args.out).write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n")
    print(json.dumps(result,ensure_ascii=False,indent=2))

if __name__ == "__main__": main()
